- name: Reissue credentials for client from valid_clients variable with OpenVPN's current PKI
# ========================================================
  # Allows caller to override hosts using '-e cmd_hosts='
  hosts: "{{ cmd_hosts | default('openvpn') }}"

  roles:
    - reissue_client
