---

- name: OpenVPN | Install | Absent all data Openvpn
  file:
    path: "{{ openvpn_path }}"
    state: absent
  when: drop_first

- name: OpenVPN | Install | Set Distro/Version specific variables
  include_vars: "{{ item }}"
  with_first_found:
    #- "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
    #- "../vars/{{ ansible_distribution }}.yml"
    - "{{ role_path }}/vars/{{ ansible_os_family }}.yml"
    #- "../vars/default.yml"
  notify:
    - clear history

- include_tasks: packages.yml
- include_tasks: pki.yml

- include_tasks: auth_db.yml
  when: enable_auth_user_password

- include_tasks: openvpn.yml
- include_tasks: 2fa_ga.yml
  when: enable_2fa
- include_tasks: firewall.yml
