---
- name: OpenVPN | Sync Clients | Register the OpenVPN server common name
  command: cat {{ openvpn_server_common_name_file }}
  no_log: true
  register: openvpn_server_common_name_result
  changed_when: false

- name: OpenVPN | Sync Clients | Set server common name variable
  set_fact:
    openvpn_server_common_name: "{{ openvpn_server_common_name_result.stdout }}"

- name: OpenVPN | Sync Clients | Get clients that are currently valid (work)
  shell: awk '/^V\s/' {{ openvpn_path_pki }}/index.txt | awk -F 'CN=' '{print $NF}' | awk -F '/' '{print $1}'
  register: currently_valid_clients_out
  changed_when: false

- name: OpenVPN | Sync Clients | Set facts
  set_fact:
    currently_valid_clients: "{{ currently_valid_clients_out.stdout.splitlines() }}"
    clients_to_revoke: [ "{{ client_to_reset }}" ]
    clients_to_add: [ "{{ client_to_reset }}" ]

- name: OpenVPN | Sync Clients | Cancel if  data is empty or not presented in valid clients list
  meta: end_play
  when: (clients_to_add | length==0) or (clients_to_revoke | length==0) or (client_to_reset not in currently_valid_clients)

- name: OpenVPN | Sync Clients | Revoke clients
  include_role:
    name: revoke_clients
  when: clients_to_revoke | length

- name: OpenVPN | Sync Clients | Add clients
  include_role:
    name: add_clients
  when: clients_to_add | length